### ISSUE TITLE
Add the possibility to change how the IncreaseMaxOrder is done

### ISSUE THREAD

**Issue by felixmusil** [cosmo-epfl/librascal#59] opened 2018-12-12 13:41 UTC
add to increase max level adaptor a template parameter to choose between different definitions of the neighborhood in the next order.
Examples of next order neighborhoods: 
+ the neighbors of the current order
+ the union of the neighbors of the current and previous order
+ the intersection of the neighbors of the current and previous order

**Comment by ceriottm** [comment] 2019-10-02 09:10
Duplicate of #31

**Closed** 2019-10-02 09:11 UTC
Labels: enhancement
