### ISSUE TITLE
Segfault when atoms are outside the periodic unit cell

### ISSUE THREAD

**Issue by max-veit** [cosmo-epfl/librascal#126] opened 2019-09-24 12:54 UTC
Many of you know what I'm talking about; this has been considered a "feature" of librascal for quite a while. But I'm marking this as a bug because a user should _never_ see a segfault for what is considered perfectly valid input for (and often, output from) a number of MD programs. (in fact, they should never see a segfault _ever_, but this is one of the most egregious examples).

If doing a simple bounds-check of the atoms before calculating the neighbourlist / applying adaptors / whatever is too performance-intensive (which I simply don't believe, especially given the tiny fraction of the total compute time it takes to build the neighbourlist in the first place), can we at least add a check in the Python interface? Something with `ase.wrap()` or whatever before the atoms are converted to `librascal` objects?

**Comment by felixmusil** [comment] 2019-09-24 15:53
I am assigning this task to you @max-veit. The wrapping of the atoms in the unit cell is simple to integrate in AtomicStructure class I think.
The segfault on very skewed cell is more tricky to understand though since it is probably a limiting case that is not properly handdled in the AdaptorNeighbourlist class.

**Comment by max-veit** [comment] 2019-09-24 16:47
Ugh. Is there an example of such a skewed cell somewhere for testing? I understand why it wouldn't be in the normal test suite (Boost can catch exceptions, but nothing can catch a segfault), but it would be good to have such an example available at least.

**Comment by felixmusil** [comment] 2019-09-24 16:59
I sent you some structures that should reproduce the segfault because it is skewed

**Comment by ceriottm** [comment] 2019-09-24 20:14
skewed cells were tested extensively by @mastricker and I believe a test should still be present somewhere. I'd be much in favor to have some basic sanity checks implemented in the release mode, possibly with a precompiler switch to turn them off if someone wants to squeeze the last flop

**Comment by felixmusil** [comment] 2019-09-24 20:50
Yes that is why it took me some time to pin point the problem.
It is not only about skewness but also triclinicity. I am talking about cells that are almost skewed but but not enough to be easily changed. The solution I found that was working has been to use spglib to sanitize the cell, the transformation is quite involved to streamline.
Since it has a c++ and python interface we can always integrate it to our project ?



Le 24 sept. 2019 22:15, Michele Ceriotti <notifications@github.com> a écrit :

skewed cells were tested extensively by @mastricker<https://github.com/mastricker> and I believe a test should still be present somewhere. I'd be much in favor to have some basic sanity checks implemented in the release mode, possibly with a precompiler switch to turn them off if someone wants to squeeze the last flop

**Comment by felixmusil** [comment] 2019-10-09 08:45
this is solved in #144

**Closed by felixmusil** 2019-10-09 08:45 UTC
Labels: bug
